include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: studio-rpc-usb-uart
# there is no settingsreset (needed) for the XIAO
